FROM almalinux:9
LABEL maintainer="G V RAO"\
     COURSE="DOCKER"\
     TOPIC="ADD vs COPY"\
     DESCRIPTION="This docker file is used to understand the difference between ADD and COPY in docker file"